/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  FreeForAllGatekeeper,
  FreeForAllGatekeeperInterface,
} from "../../../../contracts/flavors/F.sol/FreeForAllGatekeeper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_maci",
        type: "address",
      },
    ],
    name: "setMaciInstance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101ab806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806313e65cf31461003b57806324b8fbf61461004e575b600080fd5b61004c61004936600461007c565b50565b005b61004c61005c3660046100b4565b5050565b80356001600160a01b038116811461007757600080fd5b919050565b60006020828403121561008e57600080fd5b61009782610060565b9392505050565b634e487b7160e01b600052604160045260246000fd5b600080604083850312156100c757600080fd5b6100d083610060565b915060208301356001600160401b03808211156100ec57600080fd5b818501915085601f83011261010057600080fd5b8135818111156101125761011261009e565b604051601f8201601f19908116603f0116810190838211818310171561013a5761013a61009e565b8160405282815288602084870101111561015357600080fd5b826020860160208301376000602084830101528095505050505050925092905056fea2646970667358221220eb7c0f703d007dbb932b58195eb88eb4fa8ada223c2e52922121661cf42fa3b264736f6c634300080a0033";

type FreeForAllGatekeeperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FreeForAllGatekeeperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FreeForAllGatekeeper__factory extends ContractFactory {
  constructor(...args: FreeForAllGatekeeperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FreeForAllGatekeeper> {
    return super.deploy(overrides || {}) as Promise<FreeForAllGatekeeper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FreeForAllGatekeeper {
    return super.attach(address) as FreeForAllGatekeeper;
  }
  override connect(signer: Signer): FreeForAllGatekeeper__factory {
    return super.connect(signer) as FreeForAllGatekeeper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FreeForAllGatekeeperInterface {
    return new utils.Interface(_abi) as FreeForAllGatekeeperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FreeForAllGatekeeper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FreeForAllGatekeeper;
  }
}
